# Generated by Django 3.0.4 on 2020-03-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardcode', models.CharField(max_length=12)),
                ('customer', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('description', models.TextField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=255)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('attachment4', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('attachment5', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
            ],
        ),
    ]
